---
- hosts: all
  become: true
  tasks:

#  - name: install apache and php
#    package:
#      name:
#        - "{{ apache_package }}"
#        - "{{ php_package }}"
#      state: latest
#      update_cache: yes


  - name: install apache2 and php  package for Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php packages packages for CentOS
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"



  - name: update repository index for CentOS
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"


  - name: update repository index Ubuntu
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"




#  - name: add PHP support for apache
#    apt:
#      name: libapache2-mod-php
#    when: ansible_distribution == "Ubuntu"




  - name: add PHP support for apache
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"


